steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'rust-app', '-f', 'Dockerfile-rust', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'nodejs-app', '-f', 'Dockerfile-nodejs', '.']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud app deploy ts-server/app.yaml --project=npm-module-registry-381816
timeout: 2000s
