steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud builds submit --timeout=2h
    gcloud app deploy ts-server/app.yaml --project=npm-module-registry-381816
