steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud app deploy ts-server/app.yaml --project=npm-module-registry-381816 --quiet --stop-previous-version --no-promote --verbosity=debug --timeout=1800s