steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'rust-builder', '-f', 'rust-builder.Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'ts-builder', '-f', 'ts-builder.Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'app-image', '-f', 'Dockerfile', '.']
