timeout: 7200s # 2 hours in seconds

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud app deploy ts-server/app.yaml --project=npm-module-registry-381816
