/*
 * ECE 461 - Spring 2023 - Project 2
 *
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: davisjam@purdue.edu
 * Generated by: https://openapi-generator.tech
 */

/// PackageMetadata : The \"Name\" and \"Version\" are used as a unique identifier pair when uploading a package.  The \"ID\" is used as an internal identifier for interacting with existing packages.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PackageMetadata {
    /// Name of a package.  - Names should only use typical \"keyboard\" characters. - The name \"*\" is reserved. See the `/packages` API for its meaning.
    #[serde(rename = "Name")]
    pub name: String,
    /// Package version
    #[serde(rename = "Version")]
    pub version: String,
    /// 
    #[serde(rename = "ID")]
    pub id: String,
}

impl PackageMetadata {
    /// The \"Name\" and \"Version\" are used as a unique identifier pair when uploading a package.  The \"ID\" is used as an internal identifier for interacting with existing packages.
    pub fn new(name: String, version: String, id: String) -> PackageMetadata {
        PackageMetadata {
            name,
            version,
            id,
        }
    }
}


