/*
 * ECE 461 - Spring 2023 - Project 2
 *
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: davisjam@purdue.edu
 * Generated by: https://openapi-generator.tech
 */

/// PackageHistoryEntry : One entry of the history of this package.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PackageHistoryEntry {
    #[serde(rename = "User")]
    pub user: Box<crate::models::User>,
    /// Date of activity.
    #[serde(rename = "Date")]
    pub date: String,
    #[serde(rename = "PackageMetadata")]
    pub package_metadata: Box<crate::models::PackageMetadata>,
    /// 
    #[serde(rename = "Action")]
    pub action: Action,
}

impl PackageHistoryEntry {
    /// One entry of the history of this package.
    pub fn new(user: crate::models::User, date: String, package_metadata: crate::models::PackageMetadata, action: Action) -> PackageHistoryEntry {
        PackageHistoryEntry {
            user: Box::new(user),
            date,
            package_metadata: Box::new(package_metadata),
            action,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "CREATE")]
    Create,
    #[serde(rename = "UPDATE")]
    Update,
    #[serde(rename = "DOWNLOAD")]
    Download,
    #[serde(rename = "RATE")]
    Rate,
}

impl Default for Action {
    fn default() -> Action {
        Self::Create
    }
}

