/*
 * ECE 461 - Spring 2023 - Project 2
 *
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: davisjam@purdue.edu
 * Generated by: https://openapi-generator.tech
 */

/// PackageQuery : 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PackageQuery {
    /// 
    #[serde(rename = "Version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// Name of a package.  - Names should only use typical \"keyboard\" characters. - The name \"*\" is reserved. See the `/packages` API for its meaning.
    #[serde(rename = "Name")]
    pub name: String,
}

impl PackageQuery {
    /// 
    pub fn new(name: String) -> PackageQuery {
        PackageQuery {
            version: None,
            name,
        }
    }
}


