/*
 * ECE 461 - Spring 2023 - Project 2
 *
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: davisjam@purdue.edu
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Package {
    #[serde(rename = "metadata")]
    pub metadata: Box<crate::models::PackageMetadata>,
    #[serde(rename = "data")]
    pub data: Box<crate::models::PackageData>,
}

impl Package {
    pub fn new(metadata: crate::models::PackageMetadata, data: crate::models::PackageData) -> Package {
        Package {
            metadata: Box::new(metadata),
            data: Box::new(data),
        }
    }
}


