/*
 * ECE 461 - Spring 2023 - Project 2
 *
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: davisjam@purdue.edu
 * Generated by: https://openapi-generator.tech
 */

/// User : 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct User {
    /// 
    #[serde(rename = "name")]
    pub name: String,
    /// Is this user an admin?
    #[serde(rename = "isAdmin")]
    pub is_admin: bool,
}

impl User {
    /// 
    pub fn new(name: String, is_admin: bool) -> User {
        User {
            name,
            is_admin,
        }
    }
}


