# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.user import User
from openapi_server.models.user_authentication_info import UserAuthenticationInfo
from openapi_server import util


class AuthenticationRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user: User=None, secret: UserAuthenticationInfo=None):
        """AuthenticationRequest - a model defined in OpenAPI

        :param user: The user of this AuthenticationRequest.
        :param secret: The secret of this AuthenticationRequest.
        """
        self.openapi_types = {
            'user': User,
            'secret': UserAuthenticationInfo
        }

        self.attribute_map = {
            'user': 'User',
            'secret': 'Secret'
        }

        self._user = user
        self._secret = secret

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AuthenticationRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The AuthenticationRequest of this AuthenticationRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self):
        """Gets the user of this AuthenticationRequest.


        :return: The user of this AuthenticationRequest.
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this AuthenticationRequest.


        :param user: The user of this AuthenticationRequest.
        :type user: User
        """
        if user is None:
            raise ValueError("Invalid value for `user`, must not be `None`")

        self._user = user

    @property
    def secret(self):
        """Gets the secret of this AuthenticationRequest.


        :return: The secret of this AuthenticationRequest.
        :rtype: UserAuthenticationInfo
        """
        return self._secret

    @secret.setter
    def secret(self, secret):
        """Sets the secret of this AuthenticationRequest.


        :param secret: The secret of this AuthenticationRequest.
        :type secret: UserAuthenticationInfo
        """
        if secret is None:
            raise ValueError("Invalid value for `secret`, must not be `None`")

        self._secret = secret
