# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class User(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, is_admin: bool=None):
        """User - a model defined in OpenAPI

        :param name: The name of this User.
        :param is_admin: The is_admin of this User.
        """
        self.openapi_types = {
            'name': str,
            'is_admin': bool
        }

        self.attribute_map = {
            'name': 'name',
            'is_admin': 'isAdmin'
        }

        self._name = name
        self._is_admin = is_admin

    @classmethod
    def from_dict(cls, dikt: dict) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The User of this User.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this User.

        

        :return: The name of this User.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this User.

        

        :param name: The name of this User.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def is_admin(self):
        """Gets the is_admin of this User.

        Is this user an admin?

        :return: The is_admin of this User.
        :rtype: bool
        """
        return self._is_admin

    @is_admin.setter
    def is_admin(self, is_admin):
        """Sets the is_admin of this User.

        Is this user an admin?

        :param is_admin: The is_admin of this User.
        :type is_admin: bool
        """
        if is_admin is None:
            raise ValueError("Invalid value for `is_admin`, must not be `None`")

        self._is_admin = is_admin
